databases:
  # - name: Fotobook-pgSQL
  #   databaseName: fotobook_q6qs         
  #   user: root             
  #   plan: free       

services:
  - type: web
    name: Fotobook 
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'  
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Fotobook-pgSQL     
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false             
      - key: WEB_CONCURRENCY
        value: 2                
