services:
  - type: web
    name: Fotobook 
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'  
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fotobook_q6qs     
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false             
      - key: WEB_CONCURRENCY
        value: 2                
